version: "3.8"
services:
 app:
  build:
   context: .
   dockerfile: api/Dockerfile
  ports:
   - "8081:8080"
  depends_on:
   - sqldata
  environment:
    AppSettings__ConnectionStrings__DefaultConnection: "Server=sqldata;Database=CarMarketAnalysisDb;User Id=sa;Password=CarMarketAnalysis@;TrustServerCertificate=True"
 sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CarMarketAnalysis@